services:
  - type: web
    name: atelier-veridique
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_URL
        value: https://atelier-veridique.onrender.com
    buildCommand: ""
    startCommand: ""
    autoDeploy: true